name: view
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  http: ^1.6.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.3
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  flutter_tts: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true # Potrzebne do automatycznego generowania lokalizacji (opcjonalnie)
  assets:
    - assets/icons/
    - assets/logo/
